---
containerd_version: 1.6.6
containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.2.0': "{{ containerd_package }}-1.2.0"
  '1.3.7': "{{ containerd_package }}-1.3.7-3.1.el7"
  '1.3.9': "{{ containerd_package }}-1.3.9-3.1.el7"
  '1.4.3': "{{ containerd_package }}-1.4.3-3.2.el7"
  '1.4.4': "{{ containerd_package }}-1.4.4-3.1.el7"
  '1.4.6': "{{ containerd_package }}-1.4.6-3.1.el7"
  '1.4.9': "{{ containerd_package }}-1.4.9-3.1.el7"
  '1.6.6': "{{ containerd_package }}-1.6.6-3.1.el8"
  'stable': "{{ containerd_package }}-1.4.9-3.1.el7"
  'edge': "{{ containerd_package }}-1.4.9-3.1.el7"
