- name: backup| etcd | Create addon dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  with_items:
    - "{{ kube_config_dir }}/tools/etcd"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: backup| etcd | Create manifests
  template: 
    src: "{{ item }}.yml.j2" 
    dest: "{{ kube_config_dir }}/tools/etcd/{{ item }}.yml"
  with_items:
    - etcd-cronjob
  register: autoops_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: backup| etcd | Apply manifests
  shell: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/tools/etcd/{{ item.item }}.yml"
  with_items: "{{ autoops_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
